name: github pages

on:
  # masterブランチにプッシュしたときjobsに記述した操作を行う
  push:
    branches:
      - master

jobs:
  file_generation:
    runs-on: ubuntu-latest

    # Node.jsのセットアップ
    steps:
      # GitHub Pagesのconfigure変更
      - name: configure-pages
        id: pages
        uses: actions/configure-pages@v3
        with:
          static_site_generator: next
      - name: setup node
        uses: actions/setup-node@v3
        with:
          node-version: '21.x'

      # yarnでpackage.jsonの依存パッケージをインストール
      - name: yarn add
        run: yarn install

      # Next.jsアプリのビルド
      - name: build
        run: yarn run build

      #########################
      # step: configure-pagesで静的サイトジェネレータを既に指定しているので不要
      #########################
      # Next.jsから静的HTMLをエクスポート
      # - name: export
      #  run: yarn run export

      # gh-pagesブランチにoutディレクトリの中身をプッシュする
      - name: upload artifact
        uses: actions/upload-pages-artifact@v2
        with:
          path: ./out

  # GitHub Pages用のコンテナにデプロイ
  deploy-pages:
    runs-on: ubuntu-latest
    needs: file_generation
    environment:
      name: github-pages
      url: ${{steps.deployment.outputs.page_url}}
    permissions:
      contents: read
      pages: write
      id-token: write
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2
